apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server-deployment
  #namespace: default
  labels:
    app: product-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-server-deployment
  template:
    metadata:
      creationTimestamp: null
      name: product-server-deployment
      labels:
        app: product-server-deployment
    spec:
      containers:
        - name: product-server
          image: pabitramaiti/product-server
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
          imagePullPolicy: Always #IfNotPresent
          ports:
          - containerPort: 8080