---
apiVersion: v1
kind: Service
metadata:
  name: product-server
  labels:
    app: product-server
spec:
  type: NodePort
  selector:
    app: product-server
  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server
spec:
  spec:
  selector:
    matchLabels:
      app: product-server
  replicas: 1
  template:
    metadata:
      labels:
        app: product-server
    spec:
      containers:
      - name: product-server
        image: pabitramaiti/product-server:latest
        ports:
        - containerPort: 8030
        livenessProbe:
          httpGet:
            path: /products
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1
