apiVersion: v1  #Kubernets API version
kind: Service   #Kubernets resource kind we are creating
metadata:       #Metadata of resource kind we are creating
  name: product-server-deployment
  #namespace: product-server-app
  labels:
    app: product-server
spec:
  type: NodePort
  selector:
    app: product-server
  ports:
  - protocol: TCP
    port: 8080  #The port that the service is running on in the cluster
    name: http
    targetPort: 8080  # The port exposed by the service
