---
apiVersion: v1
kind: Service
metadata:
  name: product-server-deployment
  labels:
    app: product-server
spec:
  type: ClusterIP
  selector:
    app: product-server
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-server
  template:
    metadata:
      name: product-server
      labels:
        app: product-server
    spec:
      containers:
      - name: product-server-deployment
        image: pabitramaiti/product-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /products
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 1
