name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: ${{ knowledgefactory.azurecr.io }}
           username: ${{ Knowledgefactory }}
           password: ${{ PkblkahIhqxu7l41jNGCL2B4anTlDvxS1bwH18YhGr+ACRBJCHhj }}
      - run: |
          docker build . -t ${{ knowledgefactory.azurecr.io }}/knowledgefactory:${{ github.sha }}
          docker push ${{ knowledgefactory.azurecr.io }}/knowledgefactory:${{ github.sha }}